version: '3.8'

services:
  app:
    build: .
    container_name: video_processor
    restart: always
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development